// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {drive} from '../models';
import {update} from '../models';
import {store} from '../models';

export function AIBusy():Promise<boolean>;

export function AIModels():Promise<Array<string>>;

export function AIStatus():Promise<ai.Status>;

export function AskAI(arg1:ai.AskRequest):Promise<ai.AskResponse>;

export function BackupNow():Promise<drive.BackupFile>;

export function CancelAI():Promise<void>;

export function CancelDriveAuth():Promise<void>;

export function CheckForUpdates(arg1:boolean):Promise<update.Status>;

export function CreateContext(arg1:string,arg2:string):Promise<store.Context>;

export function CreateHorizon(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<store.Horizon>;

export function CreateTask(arg1:store.TaskInput):Promise<store.TaskDetail>;

export function DeleteContext(arg1:string):Promise<void>;

export function DeleteDriveBackup(arg1:string):Promise<void>;

export function DeleteHorizon(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DisconnectDrive():Promise<void>;

export function DownloadUpdate():Promise<update.Download>;

export function ExePath():Promise<string>;

export function FinishTask(arg1:string):Promise<store.TaskDetail>;

export function GetAIModel():Promise<string>;

export function GetActiveContextTimer(arg1:string):Promise<store.Context>;

export function GetActiveTimer():Promise<store.TaskDetail>;

export function GetContext(arg1:string,arg2:string):Promise<store.Context>;

export function GetContextToday(arg1:string,arg2:string):Promise<number>;

export function GetDBPath():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetDriveStatus():Promise<drive.Status>;

export function GetSettings():Promise<Record<string, string>>;

export function GetStats():Promise<store.Stats>;

export function GetTask(arg1:string):Promise<store.TaskDetail>;

export function GetVersion():Promise<string>;

export function ImportDatabaseFile(arg1:string):Promise<void>;

export function InstallUpdateAndRestart():Promise<void>;

export function ListContextEntries(arg1:string):Promise<Array<store.ContextTimeEntry>>;

export function ListContexts(arg1:string):Promise<Array<store.Context>>;

export function ListDriveBackups():Promise<Array<drive.BackupFile>>;

export function ListHorizons():Promise<Array<store.Horizon>>;

export function ListTasks(arg1:store.TaskFilter):Promise<Array<store.TaskDetail>>;

export function ListTimeEntries(arg1:string):Promise<Array<store.TimeEntry>>;

export function MoveTask(arg1:string,arg2:string):Promise<store.TaskDetail>;

export function OpenDataFolder():Promise<string>;

export function PickDatabaseFile():Promise<string>;

export function PollDriveAuth():Promise<drive.DevicePoll>;

export function QuitApp():Promise<void>;

export function ReportError(arg1:string):Promise<void>;

export function RestoreDriveBackup(arg1:string):Promise<void>;

export function SaveDriveCredentials(arg1:string,arg2:string):Promise<void>;

export function SetAIModel(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartContextTimer(arg1:string):Promise<store.Context>;

export function StartDriveAuth():Promise<drive.DeviceAuth>;

export function StartTimer(arg1:string):Promise<store.TaskDetail>;

export function StopContextTimer(arg1:string):Promise<store.Context>;

export function StopTimer(arg1:string):Promise<store.TaskDetail>;

export function ToggleFocus(arg1:string):Promise<store.TaskDetail>;

export function UpdateContext(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string,arg8:string):Promise<store.Context>;

export function UpdateHorizon(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<store.Horizon>;

export function UpdateTask(arg1:string,arg2:store.TaskInput):Promise<store.TaskDetail>;
