// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIBusy() {
  return window['go']['main']['App']['AIBusy']();
}

export function AIModels() {
  return window['go']['main']['App']['AIModels']();
}

export function AIStatus() {
  return window['go']['main']['App']['AIStatus']();
}

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function CancelAI() {
  return window['go']['main']['App']['CancelAI']();
}

export function CancelDriveAuth() {
  return window['go']['main']['App']['CancelDriveAuth']();
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function CreateContext(arg1, arg2) {
  return window['go']['main']['App']['CreateContext'](arg1, arg2);
}

export function CreateHorizon(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateHorizon'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function DeleteDriveBackup(arg1) {
  return window['go']['main']['App']['DeleteDriveBackup'](arg1);
}

export function DeleteHorizon(arg1) {
  return window['go']['main']['App']['DeleteHorizon'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DisconnectDrive() {
  return window['go']['main']['App']['DisconnectDrive']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExePath() {
  return window['go']['main']['App']['ExePath']();
}

export function FinishTask(arg1) {
  return window['go']['main']['App']['FinishTask'](arg1);
}

export function GetAIModel() {
  return window['go']['main']['App']['GetAIModel']();
}

export function GetActiveContextTimer(arg1) {
  return window['go']['main']['App']['GetActiveContextTimer'](arg1);
}

export function GetActiveTimer() {
  return window['go']['main']['App']['GetActiveTimer']();
}

export function GetActiveTimers() {
  return window['go']['main']['App']['GetActiveTimers']();
}

export function GetContext(arg1, arg2) {
  return window['go']['main']['App']['GetContext'](arg1, arg2);
}

export function GetContextTasksTotal(arg1) {
  return window['go']['main']['App']['GetContextTasksTotal'](arg1);
}

export function GetContextToday(arg1, arg2) {
  return window['go']['main']['App']['GetContextToday'](arg1, arg2);
}

export function GetContextTotal(arg1) {
  return window['go']['main']['App']['GetContextTotal'](arg1);
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDriveStatus() {
  return window['go']['main']['App']['GetDriveStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskToday(arg1, arg2) {
  return window['go']['main']['App']['GetTaskToday'](arg1, arg2);
}

export function GetTaskTotal(arg1) {
  return window['go']['main']['App']['GetTaskTotal'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportDatabaseFile(arg1) {
  return window['go']['main']['App']['ImportDatabaseFile'](arg1);
}

export function InstallUpdateAndRestart() {
  return window['go']['main']['App']['InstallUpdateAndRestart']();
}

export function ListContextEntries(arg1) {
  return window['go']['main']['App']['ListContextEntries'](arg1);
}

export function ListContexts(arg1) {
  return window['go']['main']['App']['ListContexts'](arg1);
}

export function ListDriveBackups() {
  return window['go']['main']['App']['ListDriveBackups']();
}

export function ListHorizons() {
  return window['go']['main']['App']['ListHorizons']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function ListTimeEntries(arg1) {
  return window['go']['main']['App']['ListTimeEntries'](arg1);
}

export function MoveTask(arg1, arg2) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function PickDatabaseFile() {
  return window['go']['main']['App']['PickDatabaseFile']();
}

export function PollDriveAuth() {
  return window['go']['main']['App']['PollDriveAuth']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReorderTasks(arg1) {
  return window['go']['main']['App']['ReorderTasks'](arg1);
}

export function ReportError(arg1) {
  return window['go']['main']['App']['ReportError'](arg1);
}

export function RestoreDriveBackup(arg1) {
  return window['go']['main']['App']['RestoreDriveBackup'](arg1);
}

export function SaveDriveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveDriveCredentials'](arg1, arg2);
}

export function SetAIModel(arg1) {
  return window['go']['main']['App']['SetAIModel'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetTaskParent(arg1, arg2) {
  return window['go']['main']['App']['SetTaskParent'](arg1, arg2);
}

export function StartContextTimer(arg1) {
  return window['go']['main']['App']['StartContextTimer'](arg1);
}

export function StartDriveAuth() {
  return window['go']['main']['App']['StartDriveAuth']();
}

export function StartTimer(arg1) {
  return window['go']['main']['App']['StartTimer'](arg1);
}

export function StopContextTimer(arg1) {
  return window['go']['main']['App']['StopContextTimer'](arg1);
}

export function StopTimer(arg1) {
  return window['go']['main']['App']['StopTimer'](arg1);
}

export function ToggleFocus(arg1) {
  return window['go']['main']['App']['ToggleFocus'](arg1);
}

export function UpdateContext(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateContext'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateHorizon(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateHorizon'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
